export * from './components/doctor-header';
export * from './components';
export * from './components/navbar';
export * from './doctor-routing.module';
export * from './doctor.component';
export * from './doctor.module';
export * from './pages';
export * from './pages/med-record-consultation-panel';
export * from './pages/med-record-creation-panel';
